### ISSUE TITLE
about the train.py

### ISSUE THREAD

**Issue by chutoutian** [bruceyang2012/Face-Alignment-with-simple-cnn#2]
hi, I ran the train.py  y=df[df.columns[:-1]].values 
but the type of y is string  , how to turn to the float? Please, thank you

**Comment by bruceyang2012** [comment]
I have not encountered this problem locally. May be there is someting wrong with the train.csv. I have re-uploaded the training set, you can try it again.

**Comment by bruceyang2012** [comment]
I have not encountered this problem locally. May be there is someting wrong with the train.csv. I have re-uploaded the training set, you can try it again.
