### ISSUE TITLE
Face Normalization

### ISSUE THREAD

**Issue by haloxhanner** [bruceyang2012/Face-Alignment-with-simple-cnn#3]
Hi,

Thank you so much this great simple tutorial that gives me great fast and simple knowledge about creating, developing and training cnn.

I want to train your simple cnn to normalize faces.

They represents what I want to reach (face normalization):

https://cdn-images-1.medium.com/max/800/1*igEzGcFn-tjZb94j15tCNA.png
http://www.i-programmer.info/images/stories/News/2016/Sept/B/face.jpg

Could you suggest any way to do it please?

Thanks.

**Comment by bruceyang2012** [comment]
Hi, in fact ,face landmark detection is the first step to face alignment (normalization). You can find the way to do it in my another [repository](https://github.com/bruceyang2012/Face-identification-with-cnn-triplet-loss/blob/master/preprocessing.py).
